// Package explainer provides an optional layer that translates deterministic
// analyzer signals into reviewer-friendly prose.
//
// The explainer NEVER decides what is risky. It only describes what the
// analyzer already flagged. Analyzer output (segments, tiers, scores) is
// final before the explainer ever runs, and the explainer cannot modify it.
package explainer

import (
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/yasserrmd/barq-witness/internal/analyzer"
	"github.com/yasserrmd/barq-witness/internal/config"
)

// IntentResult is returned by IntentMatch.
type IntentResult struct {
	// Score is between 0.0 and 1.0.  1.0 means the diff exactly matches
	// the prompt.  Below 0.5 means significant divergence.
	Score float64
	// Reasoning is one sentence describing the score.
	Reasoning string
}

// Explainer translates deterministic signals into prose and checks intent.
type Explainer interface {
	// Name returns the backend identifier (null, claude, groq, local).
	Name() string
	// Available returns true if the backend is reachable and configured.
	Available() bool
	// Explain returns a two-sentence factual description of why the segment
	// was flagged.  It must never change the segment's tier or score.
	Explain(ctx context.Context, segment analyzer.Segment) (string, error)
	// IntentMatch checks whether a diff matches what the prompt asked for.
	IntentMatch(ctx context.Context, prompt string, diff string) (IntentResult, error)
	// Close releases any resources (connections, goroutines).
	Close() error
}

// New constructs the Explainer selected by cfg.Explainer.Backend.
// If the selected backend is unavailable it logs a warning and falls back
// to NullExplainer so the report always succeeds.
func New(cfg *config.Config, witnessDir string) Explainer {
	logger := openExplainerLog(witnessDir)
	privacy := cfg.Privacy.Mode

	var e Explainer
	switch cfg.Explainer.Backend {
	case "claude":
		e = NewClaude(cfg.Explainer.Model, cfg.Explainer.TimeoutMS, logger, privacy)
	case "groq":
		e = NewGroq(cfg.Explainer.Model, cfg.Explainer.TimeoutMS, logger, privacy)
	case "local":
		e = NewLocal(cfg.Explainer.Model, cfg.Explainer.Endpoint,
			cfg.Explainer.TimeoutMS, logger, privacy)
	case "edge":
		e = NewEdge(cfg.Explainer.Model, cfg.Explainer.Endpoint,
			cfg.Explainer.TimeoutMS, logger, privacy)
	default:
		return NewNull()
	}

	if !e.Available() {
		logger.Printf("explainer: backend %q is not available, falling back to null", cfg.Explainer.Backend)
		return NewNull()
	}
	return e
}

// EnrichSegments calls Explain for every segment in place.
// If Explain returns an error, the deterministic template is used as the
// fallback.  Tier and Score are never touched.
func EnrichSegments(ctx context.Context, e Explainer, segments []analyzer.Segment) {
	if e.Name() == "null" {
		// NullExplainer already returns deterministic templates; no round-trip needed.
		for i := range segments {
			if segments[i].Explanation == "" {
				text, _ := e.Explain(ctx, segments[i])
				segments[i].Explanation = text
			}
		}
		return
	}

	timeout := 5 * time.Second
	for i := range segments {
		rctx, cancel := context.WithTimeout(ctx, timeout)
		text, err := e.Explain(rctx, segments[i])
		cancel()
		if err != nil || text == "" {
			// Fallback: use the deterministic template from NullExplainer.
			text, _ = NewNull().Explain(context.Background(), segments[i])
		}
		segments[i].Explanation = text
	}
}

// openExplainerLog opens .witness/explainer.log; falls back to discard on error.
func openExplainerLog(witnessDir string) *log.Logger {
	path := filepath.Join(witnessDir, "explainer.log")
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return log.New(io.Discard, "", 0)
	}
	return log.New(f, "", log.LstdFlags|log.Lmicroseconds)
}

// buildExplainPrompt constructs the standard Explain prompt from a segment.
func buildExplainPrompt(seg analyzer.Segment, privacyMode bool) string {
	promptText := seg.PromptText
	if privacyMode {
		promptText = "[redacted -- privacy mode]"
	}

	executed := "no"
	if seg.Executed {
		executed = "yes"
	}
	modified := "no"
	if seg.Modified {
		modified = "yes"
	}

	acceptedStr := "unknown"
	if seg.AcceptedSec >= 0 {
		acceptedStr = fmt.Sprintf("%d", seg.AcceptedSec)
	}

	return fmt.Sprintf(
		`You are explaining a deterministic code review signal to a tired engineer. `+
			`Do not assess whether the code is good or bad. `+
			`Only describe, in two sentences maximum, what happened during the AI coding session `+
			`that caused this signal to fire. Be concrete and reference the specific facts.`+
			"\n\nFacts:\n"+
			"- File: %s\n"+
			"- Lines: %d-%d\n"+
			"- Generated by: %s\n"+
			"- Time from prompt to acceptance: %s seconds\n"+
			"- Was the code executed locally before commit: %s\n"+
			"- Was it modified by the human after generation: %s\n"+
			"- Reason codes: %v\n"+
			"\nOriginal prompt the human gave to the AI: %s\n"+
			"\nTwo-sentence factual explanation:",
		seg.FilePath, seg.LineStart, seg.LineEnd,
		seg.SessionID, // model field not on Segment; use session as proxy
		acceptedStr, executed, modified,
		seg.ReasonCodes, promptText,
	)
}

// buildIntentPrompt constructs the IntentMatch prompt.
func buildIntentPrompt(prompt, diff string) string {
	return fmt.Sprintf(
		`You are checking whether an AI coding result matches what the human asked for. `+
			`Output strict JSON only, no prose. `+
			`Schema: {"score": float between 0 and 1, "reasoning": one short sentence}. `+
			`A score of 1.0 means the diff exactly does what the prompt asked. `+
			`A score below 0.5 means the diff diverges significantly from the request.`+
			"\n\nPrompt: %s\n\nDiff: %s\n\nJSON:",
		prompt, diff,
	)
}
