package render

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/yasserrmd/barq-witness/internal/analyzer"
)

// HTML comment marker embedded in every barq-witness PR comment so the GitHub
// Action can find and update it instead of posting a new one.
const CommentMarker = "<!-- barq-witness:comment-marker -->"

// MarkdownOptions controls the markdown renderer.
type MarkdownOptions struct {
	// TopN limits the number of segments shown (0 = all).
	TopN int
}

// Markdown writes a GitHub-flavoured markdown attention map for report to w.
func Markdown(w io.Writer, report *analyzer.Report, opts MarkdownOptions) error {
	segments := report.Segments
	if opts.TopN > 0 && len(segments) > opts.TopN {
		segments = segments[:opts.TopN]
	}

	// Hidden marker for GitHub Action comment-update detection.
	fmt.Fprintln(w, CommentMarker)
	fmt.Fprintln(w, "# barq-witness attention map")
	fmt.Fprintln(w, "")

	// Summary table.
	fmt.Fprintf(w, "| | |\n|---|---|\n")
	fmt.Fprintf(w, "| Commit range | `%s` |\n", report.CommitRange)
	fmt.Fprintf(w, "| Generated at | %s |\n", time.UnixMilli(report.GeneratedAt).UTC().Format(time.RFC3339))
	fmt.Fprintf(w, "| Total segments | %d |\n", report.TotalSegments)
	fmt.Fprintf(w, "| Tier 1 (critical) | %d |\n", report.Tier1Count)
	fmt.Fprintf(w, "| Tier 2 (elevated) | %d |\n", report.Tier2Count)
	fmt.Fprintf(w, "| Tier 3 (informational) | %d |\n", report.Tier3Count)
	fmt.Fprintln(w, "")

	if len(segments) == 0 {
		fmt.Fprintln(w, "_No flagged segments found._")
		return nil
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "")

	seenReasons := map[string]bool{}

	for i, seg := range segments {
		lineRange := ""
		if seg.LineStart > 0 || seg.LineEnd > 0 {
			lineRange = fmt.Sprintf(" lines %d-%d", seg.LineStart, seg.LineEnd)
		}

		tierBadge := tierBadge(seg.Tier)
		fmt.Fprintf(w, "### %d. %s `%s`%s\n\n", i+1, tierBadge, seg.FilePath, lineRange)

		// Flags table.
		fmt.Fprintln(w, "| Field | Value |")
		fmt.Fprintln(w, "|---|---|")
		for _, r := range seg.ReasonCodes {
			seenReasons[r] = true
			fmt.Fprintf(w, "| Flag | `%s` -- %s |\n", r, expandTemplate(r, seg))
		}

		// Explainer-provided (or deterministic fallback) explanation.
		if seg.Explanation != "" {
			fmt.Fprintf(w, "| Explanation | %s |\n", mdEscape(seg.Explanation))
		}

		// Prompt snippet.
		if seg.PromptText != "" {
			truncated := truncate(seg.PromptText, 200)
			fmt.Fprintf(w, "| Prompt | %s |\n", mdEscape(truncated))
		}

		// Timing.
		genTime := time.UnixMilli(seg.GeneratedAt).UTC().Format("15:04:05 UTC")
		acceptStr := "unknown"
		if seg.AcceptedSec >= 0 {
			acceptStr = fmt.Sprintf("%ds", seg.AcceptedSec)
		}
		execStr := "executed"
		if !seg.Executed {
			execStr = "never executed"
		}
		fmt.Fprintf(w, "| Timing | generated %s, accepted in %s, %s |\n", genTime, acceptStr, execStr)
		fmt.Fprintln(w, "")
	}

	// Reason code glossary.
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "## Why was this flagged?")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "| Code | Tier | Meaning |")
	fmt.Fprintln(w, "|---|---|---|")

	glossary := []struct{ code, tier, desc string }{
		{"NO_EXEC", "1", "Edit in trace but no execution touched the file before the commit."},
		{"FAST_ACCEPT_SECURITY", "1", "Security-sensitive path accepted in under 5 seconds."},
		{"TEST_FAIL_NO_RETEST", "1", "A test failed, code was re-generated, tests were never re-run."},
		{"HIGH_REGEN", "2", "Same file edited 4+ times in a 10-minute window."},
		{"NEVER_REOPENED", "2", "File never accessed by any subsequent tool after generation."},
		{"LARGE_MULTIFILE", "2", "Session touched more than 10 distinct files."},
		{"NEW_DEPENDENCY", "3", "Edit modified a dependency manifest."},
		{"FAST_ACCEPT_GENERIC", "3", "Edit accepted in under 3 seconds."},
		{"LONG_GENERATED_BLOCK", "3", "Single tool call added more than 100 lines."},
	}
	for _, g := range glossary {
		if !seenReasons[g.code] {
			continue
		}
		fmt.Fprintf(w, "| `%s` | %s | %s |\n", g.code, g.tier, g.desc)
	}
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "_Generated by [barq-witness](https://github.com/yasserrmd/barq-witness) -- deterministic, no LLM._")

	return nil
}

func tierBadge(tier int) string {
	switch tier {
	case 1:
		return "**[TIER 1]**"
	case 2:
		return "**[TIER 2]**"
	case 3:
		return "[TIER 3]"
	default:
		return "[TIER ?]"
	}
}

// mdEscape escapes pipe characters that would break markdown table cells.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "&#124;")
}
